### ISSUE TITLE
Simple Guide

### ISSUE THREAD

**Issue by dickermoshe** [birdcar/django-planetscale#1]
This would be an extremely useful package if you included a very simple explanation of how to use it.

**Comment by birdcar** [comment]
Hey @dickermoshe! I completely agree. 

Right now, the lack of documentation is purposeful because the package was built over the course of a couple of hours to prep for an interview and as a result the code is thoroughly untested and likely to cause issues in production.

If I find time to get testing done and also ensure that it works as expected I'll absolutely add thorough documentation on how to use it.

Additionally, contributions are very very welcome!
